### ISSUE TITLE
wrong video posted on the Learn Site

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/bootstrap-grid-system#1]
The video embedded in the Learn Site for this lesson is the same one from the previous lesson. I went to youtube to get it, but maybe it should be corrected on the Learn site. Thanks! Nicole

**Comment by AnnJohn** [comment]
Hi @nicolefederici for this video this should be this one- https://www.youtube.com/watch?v=3RqaVBTthuk

for the previous lesson, it should be this video- https://www.youtube.com/watch?v=o5UCDvaNLd8

Are you seeing something different on Learn?

**Comment by gj** [comment]
Hi @nicolefederici !

Closing this per Ann's comment above. Looks like it's still the correct video.

Thanks!
