### ISSUE TITLE
Saw a 404 error

### ISSUE THREAD

**Issue by pcherian10** [learn-co-curriculum/bootstrap-grid-system#3]
Sorry, something went wrong.

A team of highly trained monkeys has been dispatched to deal with this situation.

If you see them, send them this information as text (screenshots frighten them):
    APkpgMV5wuo85xEzzKukTxWarptpQYdZSv6xVRdaIJ-l6D5RJPkpHdhY
    vUsMdTpnyk_442hqOR_3Fpn7Ue-ZFQzdTu8WtO71i4rbU-p9DWJt6Z_7
    Qalg3_kOCgtm-PSo88nOTvcQ-3AlXQm8nT-aDyp-yz0w8cAMeTI05eyI
    6oO7oT-bfvabWGn_ajhcqMmE3EIav7heAfjtpZ-dSY3xq250BjAr7Y7l
    FCMy9qQaBoK8WRDWQV0D_moV6VPqzFPQ4gyxLe2FA_8kp-1hY60sEUjR
    ULPd1jWV-PNYq9NaFRMiTbWpri0tUINOvMPS3GHemTLf_ueKcP2-qezk
    lSdShC8I7fr0qNn2jKgfmRTZfPWFo2vWlUmEQEIahue6OtTU4GW6KYGu
    tW4HpQnAPUou_ciTWz31w6ZlSTFw9AloJqQ64wMTl8MFp69uLRrHbInC
    d3NfbBUVufvhMsGtFHgSkSoadMnIJS0LF-I24ga9MfdUO6pcYp2NDIMy
    ueTZH-6xEEF6blTOh6bvkAWkgVOyzHmlRj5pmePt8gxn2OPUIyCYCgzA
    Sbi-YhzD34SNL_lv78CbGsj3Nqxi9LbNZE1vo3mlkMG5mRLYiVYF0PgL
    S9UphqA-imKqeeWIM2Q9R8MmyZLadnVM3apd18MWc2Yk9PnhdC2guhlK
    xlO9dAd3IKxHFFRfQ56FarjzfcgD_mzojdxI_wll7h4yuII6nCirs3Yu
    gXv1rqYkSTK7x-uS7NDXNKFeRpUVyQQx7gnLI9dXT7lPHeiOWQAhmpth
    UlsGXe04jQP6iI89Q231yU8AEy-NUfTmRkWGXHj6fPH98PJTZA4SFJZo
    4wiv2_bC2FJkGHmc3qCnOLu3SLYXlJUNrIbhyFteSyBB_AvmSt5xLBL2
    TJau2HuPFpO6Thu3gDXFkykv3jkj4s4GJEgp5fSllwO43Q6-pV0F-I6o
    v13emWB_usBNi_LqdpfWkl0MQUcRP2Nprwj3R8T_fSPk2VRhzMC_TWwo
    6PtgpHjVw89ERPfSJoLGsFCb-AvENRvX84fZqiS7-ELaykkr2kQAp5i6
    g11tweOzYQGJntcQSK96-7fWlf3Y5hwYiuMzk0AHMq4mYBgRgENQ70sA
    SX2k0tswJ8Q-hRU34zk2M4e9pAVrObdbgWVlou75yEilP8ZtQzfiD3r1
    Gu4qCNFN9mmv6cK8gYxv4n1AAES1TRVK8ALmS_d3Es7EL1ttqlykS6Pt
    -wEWJqAM7UZOvhGfEdi4RL7VE-T_0BsN3kSsI4u5u8TeBh5Sm5y7Rt0C
    kiffZC4zpM-2RnFxKb0u-QS3tE0i0cey7iwB2cwe9iDlVdtxyV5jJ8rt
    vhxKo2nv-SGZQsVWLE0ESuLsZ9AAMo1F9lNDca9jOEpOC__HDnBGXNz1
    iP-qft7pW4nyJSxgRkozOJP8ywSQIkjg-HGQShiQ-yM7PSrDJSnnl5oz
    rJRmKpNSMc18BYTGiHZ8A4pFC02ycFlQ3iRhD6-SBuBVTsKyguul0vsH
    NTd4-HrkAinsx2C-dYZh_MjWjm17r9HvUAiqtgKn7Zc58_Y8yC55_YBC
    QppPtPeH_yNPHznaN0N44Kx-MPuqLZaneplVJzl5_Kg6oOXY8lJqBfSR
    BVXOdBvCBB6LBFXgUYSGLwsYdEu2R1eaYVVqGfG2eGVBrstdqHW6jwvi
    ncz682fQDC8VUZD-jCaXJ1UfFnEHKBJxNAOim-aiKhAB0UKnyR-zsEui
    2YahNow63xOEKjRwC0x-EsiPUWH08xw6WLOumucXSpF4H1gqcy-Q-YLe
    OEj8ROefaysP3aSYw1JeuOQgignbD0iNfkKNyg_1cSkcjHcrdrUEAi3n
    5C_CHIygulHfoufWOz9WDEwdXXRcrxzXtI1MMrzRiM_PGyoK8oIRYHhL
    v-HdKZgJkSldlZRb_9pz5ouuncpPB6Z1gusmsuNpIBUWF3TQ5NsYxxpX
    QmSn2-MqWu2UJSPLp0ICiK4PksFrnfyGBxWYHGjl5ZdXPvu0d0DQbIhK
    u7eufdPtRncgpP3luSYqJvgxPmof2fJXrSOk5uo-BAJzm9psHbXfjKVK
    9OZpE_2PgN5A80VZyoOlYQ

**Comment by jenmyers** [comment]
Unfortunately, we're not certain of the context of this and the problem has not been replicated. Closing.
